### ISSUE TITLE
To-do list before moving over to new server

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#13]
Let's put together the detailed list of items that need to occur prior to moving the Rescue America instance of CSR to the new server.

**Comment by ryandiks** [comment]
1. Training on reporting system Issue #11 
2. Training on creating users
3. Redirect on old URL Issue #10 
4. Migrating current data from old server to new server
5. Setting date for migration
6. ?

**Comment by ryandiks** [comment]
6. Verify that SMS messaging is working as expected

**Comment by ryandiks** [comment]
Issues #5 , #6 and #7 should be complete as well on new server.

**Comment by ryandiks** [comment]
Can we set a date of Tuesday, May 14 to be ready to migrate? That will give us a couple of days to test and then a cutover date can be planned for the weekend perhaps?

**Comment by natedl98** [comment]
Tentatively yes

I want to say I already have a migration script somewhere for yall but I need to check on that.

**Comment by ryandiks** [comment]
Does the migration script have the ability to move over current usernames/passwords?

**Comment by ryandiks** [comment]
Add:

7. User acceptance testing

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
