### ISSUE TITLE
How to Sign Up Users

### ISSUE THREAD

**Issue by natedl98** [natedl98/csr-rh#16]
1) Have the User Sign up at RH's signup link: https://crowdsourcerescue.com/campaign-subscriptions/add-user/8/498?scope_campaigns=8

You can also view this link on the campaign home page here:
![Screenshot from 2019-05-10 22:20:19](https://user-images.githubusercontent.com/20713045/57564477-ee6b0300-7371-11e9-8f7d-af8fd04b26a2.png)

Once they sign up, they are officially in RH's campaign. However, I have setup the security permissions so that they cannot view anything yet, until they belong to a group that has permission to view everything.

2) Once they have signed up, you must add them to the **On-Call Staff** group (this group is the one that is allowed to access the RH homepage and view reports, etc). You can access the Add/Remove Members interface for this group via a link on the homepage as well:

![Screenshot from 2019-05-10 22:24:41](https://user-images.githubusercontent.com/20713045/57564516-8963dd00-7372-11e9-8f2b-391f138b89a8.png)

3) This next page is not intuitive, and I am very much open to improving it if you have ideas. The basic idea behind this page is that it has a list of every member of the group (so, in this case, the group is **On-Call Staff**) and then you can add or remove members from the group. The unclear part is that in order to add members that are not already in the group, you have to search from a pool of all users to find the ones you'd like to add, at which point you can add them. In your case, it would make sense to just list every user instead of making you search, but in most use cases for us, there are thousands of users in any given campaign, so showing a list of all users wouldn't be the best way.

Anyway, here is the process:

Hit the search button. In your case, you won't have to actually provide any search parameters since you won't have a large amount of users. So by hitting the search button without providing any search parameters, it will just return a list of all users
![Screenshot from 2019-05-10 22:33:33](https://user-images.githubusercontent.com/20713045/57564606-312dda80-7374-11e9-8624-ec6003084cc8.png)

Select the person you want to add, check their checkbox, and hit "Add/Remove Members"
![Screenshot from 2019-05-10 22:34:58](https://user-images.githubusercontent.com/20713045/57564620-5e7a8880-7374-11e9-844c-b85260352415.png)

That should be it. The new user may have to log out and log in for the new permissions to be in effect for them (hopefully I'll fix that sooner rather than later but for now it's a minor inconvenience that they'll only have to do once)

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
