### ISSUE TITLE
Form link in Ticket Creation Pipeline change?

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#17]
The link in the SMS sent by the Ticket Creation Pipeline brings the reader to a follow up form. The preferred action would be to match current behaviour (on memegle) which brings up the filled out intake form with the follow up form appended.

What link text would accomplish this?

memeagle has link as : memegle.com/tickets/edit/1168/9?scope_campaigns=8

![Screenshot_20190521-151523_Messages](https://user-images.githubusercontent.com/49453047/58127952-2da01c00-7bdc-11e9-86b8-d16aa981a9e4.jpg)

That's the "new" behaviour on crowdsourcerescue.com (screenshot)

**Comment by ryandiks** [comment]
Or, if it is not possible to have the intake form plus a followup form on one page, then it would be a link to the filled out intake form with a link to a followup form. But the person filling out the followup for the first time prefers to be able to read the intake form while doing the initial followup.

**Comment by natedl98** [comment]
I had forgotten about this. I'll see if I can do a similar hack for yall tomorrow on the new site. Ideally we have it presented in the formsbuilder so you can choose which datapoints you'd like to display alongside the form, but in the interests of time for now I'll probably just hardcode it only for yall

**Comment by natedl98** [comment]
Alright, I have applied the same hack as before for this

**Comment by ryandiks** [comment]
Confirmed. The form is looking how our users want it.

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
