### ISSUE TITLE
New Datapoints needed

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#18]
I tried to create my own datapoints and the site does nothing after pressing the "Save" button. Can you add these to our campaign? 

1. First time caller to the hotline?
   - I did create a question on the Intake Form that asks this question, but cannot seem to report on it since it did not create a related datapoint.

2. Name of form submitter
  - This would be a dropdown form that we can edit as needed containing the names of volunteers who are filling the form out. It's not a perfect system but it allows us to contact our volunteer if necessary.

**Comment by ryandiks** [comment]
You can scratch the second data point request. I was able to do it differently.

**Comment by ryandiks** [comment]
As for the datapoint for a first time caller, the intake form editor shows that the datapoint is created, but I cannot seem to find it for creating reports.

**Comment by natedl98** [comment]
Yeah, so the way I usually do this is:
1) I add the question to a form
2) I go to the interface at https://crowdsourcerescue.com/campaigns/datapoints/8?scope_campaigns=8 to then add the datapoint to the list of presented datapoints

I did this for the "first time caller" datapoint and it appears to be showing up now for reports. This process is kind of a mess, so I am open to more intuitive ways of doing it. But for now, this at least works

**Comment by ryandiks** [comment]
![image](https://user-images.githubusercontent.com/49453047/58488493-0b078900-812f-11e9-997c-b74d45e7d035.png)

When I try adding a new datapoint, I get to this screen and cannot search for a datapoint. And if I try to add the one that I created on the form, nothing happens when I click the "Add" button.

**Comment by ryandiks** [comment]
Are there different permissions needed to be able to make datapoint changes? I still cannot fully add datapoints or edit the list.

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
