### ISSUE TITLE
Ensure Hotline Intake form is public

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#19]
The Intake form needs to be publicly accessible so we do not have to assign logins to each of our volunteers. Can you ensure that the form is public? Or provide the steps that I can follow to make it public?

**Comment by natedl98** [comment]
![Screenshot from 2019-05-24 18:18:51](https://user-images.githubusercontent.com/20713045/58360835-78c26500-7e50-11e9-9555-49713b5e2791.png)

So, if you go the formbuilder for this form (https://crowdsourcerescue.com/forms/edit/8?scope_campaigns=8) and go to the bottom, you should see "Choose playbook" and a dropdown menu. Select the default playbook and it should pop open the permissions switchboard, where you can enable the 'Fill out' permission (permissions on the y-axis) for the 'Public' role (roles on the x-axis).

**Comment by ryandiks** [comment]
Thanks! I've updated those permissions. Does it take any period of time to become active?

**Comment by natedl98** [comment]
Should be active immediately

**Comment by ryandiks** [comment]
What link would I use then? I fully admit that I can be doing something wrong.

**Comment by natedl98** [comment]
ok, this should be good now. I forgot- we've got a master switch, for access to forms in general, that also needed to be flipped on (in addition to the switch for this particular form).

**Comment by ryandiks** [comment]
Confirmed. https://crowdsourcerescue.com/tickets/add/8?scope_campaigns=8 is available to the public now. Thanks!

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
