### ISSUE TITLE
SMS messaging changes

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#20]
New SMS message has:

CrowdSource Rescue User Says:

[Text that we can customize]

(CrowdSource Rescue not responsbile...)

Can we remove the header and footer notes outside of our customizable text?

**Comment by natedl98** [comment]
yeah, I'll see if I can get to this today

**Comment by natedl98** [comment]
ok, I made some changes. Mind letting me know once it has been tested?

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
