### ISSUE TITLE
Viewing All Tickets - Make Header Bar float/static

### ISSUE THREAD

**Issue by ryandiks** [natedl98/csr-rh#6]
When users are scrolling through the All Tickets list, the header row does not stay affixed to the top of the page which would allow the user to keep track of what each column's information is.

Can we make the header row become a floating/static item?

**Comment by natedl98** [comment]
Yeah this one has been on the to-do list for a while but keeps getting pushed down

**Comment by ryandiks** [comment]
See the new header bar and it is staying in place!

**Comment by ryandiks** [comment]
Closing ticket. Implemented with cutover.
